### ISSUE TITLE
A question about the api

### ISSUE THREAD

**Issue by antoniguss** [Delitefully/spotify-canvas-downloader#3]
Hi, I just found your project and I must say, I'm really impressed with it. The downloader page is really cool, and I wanted to try and use the API you mentioned in the README part. What is the correct way to use it? Is there a way to access it programmatically, by making GET requests?

**Comment by Delitefully** [comment]
I do have a hosted version of it for https://canvastify.delitefully.com, however I'd much rather you hosted your own instance if you need to use it for anything that's not small scale.

GET api.delitefully.com/api/canvas/:trackID

**Comment by antoniguss** [comment]
Thank you for your response, I wanted to try the api out to see if It would work for me and if it does I will definitely host it on my machine.
